modules/management/controllers/DefaultController.php
<?php

namespace app\modules\management\controllers;

use app\models\User;
use Yii;
use yii\web\Controller;

/**
 * Default controller for the `management` module
 */
class DefaultController extends BaseController
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->redirect(['product/']);
//        return $this->render('index');
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['auth/login']);
    }

}

modules/management/views/layouts/_footer.php
<!--<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>document.write(new Date().getFullYear())</script> © Nazox.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right d-none d-sm-block">
                    Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesdesign
                </div>
            </div>
        </div>
    </div>
</footer>
-->

modules/management/views/layouts/_header.php
<?php

use app\modules\management\services\UserService;
use yii\helpers\Url;

?>
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="index.html" class="logo logo-dark">
                                <span class="logo-sm">
                                    <img src="/img/svgSprite.svg#logo__cheburek" alt="" height="22">
                                </span>
                    <span class="logo-lg">
                                    <img src="/img/svgSprite.svg#logo__cheburek" alt="" height="20">
                                </span>
                </a>

                <a href="index.html" class="logo logo-light">
                                <span class="logo-sm">
                                    <img src="/backend_assets/images/logo-sm-light.png" alt="" height="22">
                                </span>
                    <!--<span class="logo-lg">
                                    <img src="/backend_assets/images/logo-light.png" alt="" height="20">
                                </span>-->
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-24 d-lg-none header-item" data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="ri-menu-2-line align-middle"></i>
            </button>
        </div>

        <div class="d-flex">
            <div class="dropdown d-inline-block d-lg-none ml-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="ri-search-line"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                     aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ...">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="ri-search-line"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="ri-fullscreen-line"></i>
                </button>
            </div>

            <div class="dropdown d-inline-block user-dropdown">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/user.png"
                         alt="Header Avatar">
                    <span class="d-none d-xl-inline-block ml-1"><?=UserService::userInfo()['email']??null?></span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item text-danger" href="<?=Url::to(['default/logout'])?>"><i class="ri-shut-down-line align-middle mr-1 text-danger"></i> Logout</a>
                </div>
            </div>
        </div>
    </div>
</header>

modules/management/views/layouts/_sidebar.php
<?php

use yii\helpers\Url;

?>
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">
            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                  <!--  <li class="nav-item">
                        <a class="nav-link" href="<?php /*=Url::to(['default/'])*/?>">
                            <i class="ri-dashboard-line mr-2"></i> Dashboard
                        </a>
                    </li>-->
                    <li class="nav-item">
                        <a class="nav-link" href="<?=Url::to(['media/'])?>">
                            <i class="ri-dashboard-line mr-2"></i> Banner
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=Url::to(['product/'])?>">
                            <i class="ri-dashboard-line mr-2"></i> Products
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=Url::to(['item-dictionary/'])?>">
                            <i class="ri-dashboard-line mr-2"></i> Item dictionary
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=Url::to(['product-category/'])?>">
                            <i class="ri-dashboard-line mr-2"></i> Product category
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=Url::to(['product-type/'])?>">
                            <i class="ri-dashboard-line mr-2"></i> Product type
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=Url::to(['faq/'])?>">
                            <i class="ri-dashboard-line mr-2"></i> Faq
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

modules/management/views/layouts/auth.php
<?php

/** @var \yii\web\View $this */
/** @var string $content */

use app\assets\ManagementAsset;
use yii\helpers\Html;


ManagementAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>
<body class="auth-body-bg">
<div class="home-btn d-none d-sm-block">
    <a href="index.html"><i class="mdi mdi-home-variant h2 text-white"></i></a>
</div>
<div>
    <?=$content?>
</div>



<!-- JAVASCRIPT -->
<script src="assets/libs/jquery/jquery.min.js"></script>
<script src="assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="assets/libs/metismenu/metisMenu.min.js"></script>
<script src="assets/libs/simplebar/simplebar.min.js"></script>
<script src="assets/libs/node-waves/waves.min.js"></script>

<script src="assets/js/app.js"></script>

</body>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage();

modules/management/views/layouts/main.php
<?php

/** @var \yii\web\View $this */
/** @var string $content */

use app\assets\ManagementAsset;
use yii\helpers\Html;


ManagementAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<body data-topbar="dark" data-layout="horizontal">

<div id="layout-wrapper">

    <?=Yii::$app->controller->renderPartial('/layouts/_header')?>
    <?=Yii::$app->controller->renderPartial('/layouts/_sidebar')?>
    <div class="main-content">
        <div class="page-content">
            <div class="container-fluid">
            <?= $content ?>
            </div>
        </div>
        <?=Yii::$app->controller->renderPartial('/layouts/_footer')?>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage();