controllers/ShopController.php
<?php

namespace app\controllers;

use app\components\PaymentStatus;
use app\components\Tinkoff;
use app\components\YooKassa;
use app\models\Cart;
use app\models\Faq;
use app\models\Media;
use app\models\PasswordChange;
use app\models\PasswordVerification;
use app\models\PaymentForm;
use app\models\ProductCategory;
use app\models\Products;
use app\models\Sales;
use app\models\SalesMain;
use app\models\search\ProductsSearch;
use app\models\User;
use app\modules\management\services\ProductService;
use app\modules\management\services\UserService;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class ShopController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function __construct($id, $module, $config = [])
    {
        if (!Yii::$app->user->isGuest) {
            (new PaymentStatus())->checkAllUserPayments(Yii::$app->user->id,true);
        }
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionAssignInventar()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $postContent = Yii::$app->request->post();
                $saleMain = new SalesMain();
                $saleMain->user_id = Yii::$app->user->id;
                $saleMain->nickname = $postContent['nickname'];
                if($saleMain->save()) {
                    foreach ($postContent['products'] as $productId) {
                        $inventar = Sales::findOne($productId);
                        if ($inventar) {
                            $inventar->sale_id = $saleMain->id;
                            $inventar->reserved_datetime = date('Y-m-d H:i:s');
                            $inventar->is_claimed = false;
                            $inventar->reserved_nickname = $postContent['nickname'];
                            $inventar->save(false);
                        }
                    }
                }
                $transaction->commit();
            } catch (\Exception $e) {
                $transaction->rollBack();
                throw $e;
            }
        }
    }

    public function actionProfile()
    {
        $model = new PasswordChange();
        $user = User::findOne(Yii::$app->user->id);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user->password = Yii::$app->security->generatePasswordHash($model->new_password);
            $user->save(false);
            Yii::$app->session->setFlash('success', 'пароль был изменен');

            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->render('profile', [
            'model' => $model
        ]);
    }

    public function actionPasswordVarification()
    {
        $model = new PasswordVerification();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = User::findOne(['email' => $model->email]);
            if ($user) {
                $user->setVerificationCode();
                $sendEmail = (new UserService())->sendVerificationEmail(
                    $user->password_verification,
                    $user->email,
                    $user->nickname
                );
                if ($sendEmail) {
                    Yii::$app->session->setFlash('success', 'Ссылка для смены почты отправлена на почту');
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('password_varification', [
            'model' => $model
        ]);
    }

    public function actionResetPassword($token)
    {
        $model = PasswordChange::findOne(['password_verification' => $token]);
        $user = User::findOne(['password_verification' => $token]);
        if (!$model) {
            return $this->redirect(['authorization']);
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user->password = Yii::$app->security->generatePasswordHash($model->new_password);
            $user->save(false);
            Yii::$app->session->setFlash('success', 'пароль был изменен');

            return $this->redirect(Yii::$app->request->referrer);
        }
        $model->password = '';
        return $this->render('reset_password', [
            'model' => $model
        ]);
    }

    public function actionCartQuantity()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax) {

            $postContent = Yii::$app->request->post();
            $model = Products::findOne($postContent['product_id']);
            if ($postContent['quantity'] > $model->quantity) {
                return [
                    'exists' => false,
                    'max_quantity' => $model->quantity,
                    'message' => 'Such quantity does not exist!'
                ];
            }
            ProductService::updateCartProduct(Yii::$app->user->id, $postContent['product_id'], $postContent['quantity']);
            $sum = 0;
            foreach (ProductService::productListInCart(Yii::$app->user->id) as $cart) {
                if ($cart['product_discounted']) {
                    $sum += $cart['discounted_price'] * $cart['quantity'];
                } else {
                    $sum += $cart['original_price'] * $cart['quantity'];
                }
            }

            return [
                'exists' => true,
                'current_quantity' => $postContent['quantity'],
                'product_sum' => $sum
            ];
        }
    }

    public function actionDeleteAllCart()
    {
        Cart::deleteAll(['user_id' => Yii::$app->user->id]);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionBuy()
    {
        $userBalance = User::findOne(Yii::$app->user->id);
        $productBalance = ProductService::productSumPrice();
        if ($userBalance->balance < $productBalance) {
            Yii::$app->session->setFlash('danger', 'отсутствие баланса!');
            return $this->redirect(Yii::$app->request->referrer);
        }

        foreach (ProductService::productListInCart(Yii::$app->user->id) as $cart) {
            $product = Products::findOne($cart['product_id']);
            if ($product->quantity < $cart['quantity']) {
                Yii::$app->session->set(sprintf('Not enough quantity is available for the product %s!, 
                the some product may have been alreadt in your invertar', $product->title), true);
                return $this->redirect(['shop/']);
            }
            $sales = new Sales();
            $sales->product_id = $cart['product_id'];
            $sales->quantity = $cart['quantity'];
            $sales->user_id = Yii::$app->user->id;
            $sales->save();
            $product->quantity -= $cart['quantity'];
            $product->save(false);
        }
        $userBalance->balance -= $productBalance;
        $userBalance->save(false);
        Cart::deleteAll(['user_id' => Yii::$app->user->id]);
        Yii::$app->session->set('sale_active', true);
        return $this->redirect(['shop/finish-sale']);
    }

    public function actionFinishSale()
    {
        $checkSession = Yii::$app->session->get('sale_active');
        if ($checkSession) {
            Yii::$app->session->remove('sale_active');
            return $this->render('thanks_page');
        }
        return $this->redirect(['shop/products']);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $categories = ProductCategory::find()->all();
        $faq = Faq::findAll(['show_homepage' => true, 'is_active' => true]);
        $discountedProduct = Products::findOne(['is_discounted' => true, 'is_active' => true]);
        $bannerImage = Media::find()->one();
        $bannerImage ? $bannerImageTitle = sprintf('/uploads/%s', $bannerImage->image_path) : $bannerImageTitle = '/assets/img__hero.webp';
        return $this->render('index', [
            'categories' => $categories,
            'faq' => $faq,
            'bannerImage' => $bannerImage,
            'bannerImageTitle' => $bannerImageTitle,
            'discountedProduct' => $discountedProduct,
        ]);
    }


    public function actionProducts()
    {
        $searchModel = new ProductsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $categoryId = Yii::$app->request->get('product_category_id');
        if ($categoryId !== null) {
            $dataProvider->query->andFilterWhere(['product_category_id' => $categoryId]);
        }
        $dataProvider->pagination->pageSize = 36;
        return $this->render('products', [

views/layouts/_cart.php
<?php

use app\modules\management\services\ProductService;
use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="page__cart">
    <div class="panel">
        <div class="panel__header">
            <div class="panel__inner">
                <h2 class="panel__title">Корзина</h2>
                <div class="panel__amount">Предметов: <span><?=ProductService::productQuantityInCart(Yii::$app->user->id)?></span></div>
            </div>
            <button class="panel__close">
                <svg class="panel__icon">
                    <use href="/img/svgSprite.svg#icon__close"></use>
                </svg>
            </button>
        </div>
        <div class="panel__scroll">
            <div class="panel__body">
                <ul class="panel__list">
                    <?php $sum = 0; ?>
                    <?php foreach (ProductService::productListInCart(Yii::$app->user->id) as $cart) : ?>
                    <li class="panel__item">
                        <div class="card-cart">
                            <div class="card-cart__header">
                                <div class="card-cart__miniature"><img class="card-cart__img"
                                                                       src="<?=$cart['product_image']?>"
                                                                       alt="Х.СВ.ЕР.ЛИ.Г.АН"/></div>
                                <div class="card-cart__info">
                                    <div class="card-cart__title"><?=$cart['product_name']?></div>
                                    <?php if ($cart['product_discounted']) : ?>
                                        <?php $sum += $cart['discounted_price']*$cart['quantity']; ?>
                                        <div class="card-cart__old-price"><span><?=number_format($cart['original_price']*$cart['quantity'])?></span> ₽</div>
                                        <div class="card-cart__price"><span><?=number_format($cart['discounted_price']*$cart['quantity'])?></span> ₽</div>
                                    <?php else : ?>
                                    <?php $sum += $cart['original_price']*$cart['quantity']; ?>
                                        <div class="card-cart__price"><span><?= number_format($cart['original_price']*$cart['quantity'])?></span> ₽</div>
                                    <?php endif; ?>

                                </div>
                            </div>
                            <div class="card-cart__footer">
                                <filedset class="number card-cart__number" id="fieldset">
                                    <button  data-product-id="<?=$cart['product_id']?>" class="number__button number__button--sub decrease" type="button">−
                                        <!--+icon('minus')(class='number__icon')--></button>
                                    <button data-product-id="<?=$cart['product_id']?>"  class="number__button number__button--add increase" type="button">+
                                        <!--+icon('plus')(class='number__icon')--></button>
                                    <input  class="number__input card-cart__number cart-number-input" type="number" min="1"
                                           value="<?=$cart['quantity']?>" pattern="[0-9]+" />
                                </filedset>
                                <a href="<?=Url::to(['shop/delete-cart','id'=>$cart['cart_id']])?>">
                                    <button class="card-cart__delete">
                                    <svg class="card-cart__icon">
                                        <use href="/img/svgSprite.svg#icon__trash"></use>
                                    </svg>
                                </button>
                                </a>
                            </div>
                        </div>
                    </li>
                    <?php endforeach; ?>
                    <?php if ($sum == 0) : ?>
                        <div class="alert alert-danger" role="alert">
                            Нет продуктов
                        </div>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
        <?php if ($sum != 0) : ?>
        <div class="panel__footer panel__footer--cart">
            <div class="panel__cart-total">
                <div class="panel__cart-total-title">К оплате:</div>
                <div class="panel__cart-total-price"><span class="overal_sum"><?=$sum?></span> ₽</div>
            </div>
            <div class="panel__cart-actions">
                <a style="text-decoration: none" href="<?=Url::to(['shop/buy'])?>"> <button class="button  button--primary panel__button"><span>Купить</span>
                </button>
                </a>
                <?= Html::a('Очистить', ['shop/delete-all-cart'], [
                    'class' => 'button  button--secondary panel__button',
                    'data' => [
                        'confirm' => 'Все товары из корзины будут удалены, вы уверены?',
                        'method' => 'post',
                    ],
                ]) ?>

            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php
$this->registerJs( <<< EOT_JS_CODE

 $(document).ready(function() {
        $('.card-cart__number').on('change', function() {
            var quantity = $(this).val();
            var productId = $(this).data('product-id');
            console.log('works');
        });
    });

EOT_JS_CODE
);
?>

views/layouts/authorized_header.php
<?php

use app\modules\management\services\ProductService;
use yii\helpers\Url;

?>
<header class="header">
    <div class="header__inner">
        <a href="/">
            <div class="header__logo">
                <svg class="logo">
                    <use href="/img/svgSprite.svg#logo__cheburek"></use>
                </svg>
            </div>
        </a>
        <div class="header__row">
            <div class="header__nav-scroll">
                <nav class="header__nav">
                    <a class="header__nav-item" href="<?=Url::to(['shop/products'])?>">Магазин</a><a
                            class="header__nav-item" href="<?=Url::to(['shop/inventar'])?>">Инвентарь</a><a class="header__nav-item"
                                                                                           href="<?=Url::to(['shop/faq'])?>">FAQ</a><a
                            class="header__nav-item" target="_blank" href="https://www.youtube.com/watch?v=VMsHB4MCV_w">Инструкция</a></nav>
            </div>
        </div>
        <div class="header__user"><a class="wallet header__wallet" href="<?=Url::to(['shop/profile'])?>">
                <svg class="wallet__icon">
                    <use href="/img/svgSprite.svg#icon__wallet"></use>
                </svg>
                <div class="wallet__title"><span><?=ProductService::showUserBalance()?></span> ₽</div>
            </a>
            <div class="header__divider"></div>
            <div class="account header__account"><a class="account__inner" href="<?=Url::to(['shop/profile'])?>">
                    <div class="account__name"><?=Yii::$app->user->identity->nickname??'User'?></div>
                    <div class="account__email"><?=Yii::$app->user->identity->email?></div>
                </a>
                <a data-method="post" href="<?=\yii\helpers\Url::to(['shop/logout'])?>">
                    <button class="account__button">
                    <svg class="account__icon">
                        <use href="/img/svgSprite.svg#icon__logout"></use>
                    </svg>
                </button>
                </a>
            </div>
        </div>
    </div>
</header>

views/layouts/main.php
<?php

/** @var yii\web\View $this */

/** @var string $content */

use app\assets\AppAsset;
use app\modules\management\services\ProductService;
use app\widgets\Alert;
use yii\bootstrap5\Breadcrumbs;
use yii\bootstrap5\Html;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;
use yii\helpers\Url;

AppAsset::register($this);

$this->registerCsrfMetaTags();
$this->registerMetaTag(['charset' => Yii::$app->charset], 'charset');
$this->registerMetaTag(['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no']);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['meta_description'] ?? '']);
$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['meta_keywords'] ?? '']);
$this->registerLinkTag(['rel' => 'apple-touch-icon', 'type' => 'image/x-icon', 'href' => '@web/img/favicon/apple-touch-icon.png']);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <?php $this->head() ?>
</head>
<?php $this->beginBody() ?>

<?php
$script = <<< JS
   function cth(c){document.documentElement.classList.add(c)}
'ontouchstart' in window?cth('touch'):cth('no-touch');
if(typeof InstallTrigger!=='undefined')cth('firefox');
if(/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==="[object SafariRemoteNotification]"})(!window['safari']||(typeof safari!=='undefined'&&safari.pushNotification)))cth('safari');
if(/*@cc_on!@*/!!document.documentMode)cth('ie');
if(!(!!document.documentMode)&&!!window.StyleMedia)cth('edge');
if(!!window.chrome&&(!!window.chrome.webstore||!!window.chrome.runtime))cth('chrome');
if(~navigator.appVersion.indexOf("Win"))cth('windows');
if(~navigator.appVersion.indexOf("Mac"))cth('osx');
if(~['iPad','iPhone','iPod'].indexOf(navigator.platform))cth('ios');
if(~navigator.appVersion.indexOf("Linux"))cth('linux');

// Добавление 1vh (использование: height: 100vh; height: calc(var(--vh, 1vh) * 100);) для фикса 100vh на мобилках
let vh = window.innerHeight * 0.01;
document.documentElement.style.setProperty('--vh', vh);
window.addEventListener('resize', () => {
  let vh = window.innerHeight * 0.01;
  document.documentElement.style.setProperty('--vh', vh);
});
JS;
$this->registerJs($script);
?>
<?php if (Yii::$app->session->getFlash('custom')) : ?>
    <?= '<script>$(`[data-panel-trigger="cart"]`).click()</script>'; ?>
<?php endif; ?>
<noscript>У вас отключен JavaScript. Это пугает.</noscript>
<div class="page">
    <div class="page__cart-badge">
        <?php if(!Yii::$app->user->isGuest): ?>
            <button class="cart-badge" data-cart-counter="<?=ProductService::productQuantityInCart(Yii::$app->user->id)?>" data-panel-trigger="cart">
                <svg class="cart-badge__icon">
                    <use href="/img/svgSprite.svg#icon__cart"></use>
                </svg>
            </button>
        <?php endif; ?>
    </div>
    <?=Yii::$app->controller->renderPartial('/layouts/_cart')?>
    <div class="page__header">
        <?php
        foreach (Yii::$app->session->getAllFlashes() as $type => $message) : ?>
            <?php if($type != 'custom'): ?>
                <div class="alert alert-<?=$type?>" role="alert"  id="flash-message">
                    <p class="text-center"><?=$message?></p>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <!--header logic-->
        <?php if (Yii::$app->user->isGuest): ?>
            <?= Yii::$app->controller->renderPartial('/layouts/unauthorized_header') ?>
        <?php else : ?>
            <?= Yii::$app->controller->renderPartial('/layouts/authorized_header') ?>
        <?php endif; ?>
    </div>

    <?= $content ?>
    <div class="page__footer">
        <footer class="footer">
            <div class="footer__inner">
                <div class="footer__logo">
                    <svg class="logo">
                        <use href="./img/svgSprite.svg#logo__cheburek"></use>
                    </svg>
                </div>
                <nav class="footer__nav"><a class="footer__nav-item" href="<?=Url::to(['shop/products'])?>">Магазин</a><a
                            class="footer__nav-item" href="<?=Url::to(['shop/inventar'])?>">Инвентарь</a><a class="footer__nav-item"
                                                                                                            href="<?=Url::to(['shop/faq'])?>">FAQ</a><a
                            class="footer__nav-item" href="https://vk.com/4ebyrekshop">Инструкция</a></nav>
                <a class="button footer__vk-button" target="_blank" href="https://www.youtube.com/watch?v=VMsHB4MCV_w">
                    <svg class="button__icon">
                        <use href="img/svgSprite.svg#icon__vk"></use>
                    </svg>
                    <span class="button__title">Группа в Вконтакте</span></a>
                <div class="footer__info">ИП Тойкиев Эмиль Алексеевич, <strong>ИНН:</strong> 023103035067, <strong>ОГРНИП:</strong> 323169000054334
                </div>
                <div class="footer__copy"><?=date('Y')?> © <strong>Cheburek</strong></div>
            </div>
        </footer>
    </div>
    <div class="page__darker"></div>
</div>
<!--<script src="/js/bundle.js"></script>-->


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/unauthorized_header.php
<?php

use yii\helpers\Url;

?>
<header class="header">
    <div class="header__inner"><a class="header__logo" href="/">
            <svg class="logo">
                <use href="/img/svgSprite.svg#logo__cheburek"></use>
            </svg>
        </a>
        <div class="header__row">
            <div class="header__nav-scroll">
                <nav class="header__nav"><a class="header__nav-item"
                                            href="<?= Url::to(['shop/products']) ?>">Магазин</a><a
                            class="header__nav-item" href="<?=Url::to(['shop/inventar'])?>">Инвентарь</a><a class="header__nav-item"
                                                                                           href="<?=Url::to(['shop/faq'])?>">FAQ</a><a
                            class="header__nav-item" target="_blank" href="https://www.youtube.com/watch?v=VMsHB4MCV_w">Инструкция</a></nav>
            </div>
        </div>
        <div class="header__user"><a class="button" href="<?= \yii\helpers\Url::to(['shop/authorization']) ?>"><span
                        class="button__title">Войти</span></a></div>
    </div>
</header>