controllers/ShopController.php
<?php

namespace app\controllers;

use app\components\PaymentStatus;
use app\components\Tinkoff;
use app\components\YooKassa;
use app\models\Cart;
use app\models\Faq;
use app\models\Media;
use app\models\PasswordChange;
use app\models\PasswordVerification;
use app\models\PaymentForm;
use app\models\ProductCategory;
use app\models\Products;
use app\models\Sales;
use app\models\SalesMain;
use app\models\search\ProductsSearch;
use app\models\User;
use app\modules\management\services\ProductService;
use app\modules\management\services\UserService;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class ShopController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function __construct($id, $module, $config = [])
    {
        if (!Yii::$app->user->isGuest) {
            (new PaymentStatus())->checkAllUserPayments(Yii::$app->user->id,true);
        }
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionAssignInventar()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax) {
            $transaction = Yii::$app->db->beginTransaction();
            try {
                $postContent = Yii::$app->request->post();
                $saleMain = new SalesMain();
                $saleMain->user_id = Yii::$app->user->id;
                $saleMain->nickname = $postContent['nickname'];
                if($saleMain->save()) {
                    foreach ($postContent['products'] as $productId) {
                        $inventar = Sales::findOne($productId);
                        if ($inventar) {
                            $inventar->sale_id = $saleMain->id;
                            $inventar->reserved_datetime = date('Y-m-d H:i:s');
                            $inventar->is_claimed = false;
                            $inventar->reserved_nickname = $postContent['nickname'];
                            $inventar->save(false);
                        }
                    }
                }
                $transaction->commit();
            } catch (\Exception $e) {
                $transaction->rollBack();
                throw $e;
            }
        }
    }

    public function actionProfile()
    {
        $model = new PasswordChange();
        $user = User::findOne(Yii::$app->user->id);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user->password = Yii::$app->security->generatePasswordHash($model->new_password);
            $user->save(false);
            Yii::$app->session->setFlash('success', 'пароль был изменен');

            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->render('profile', [
            'model' => $model
        ]);
    }

    public function actionPasswordVarification()
    {
        $model = new PasswordVerification();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = User::findOne(['email' => $model->email]);
            if ($user) {
                $user->setVerificationCode();
                $sendEmail = (new UserService())->sendVerificationEmail(
                    $user->password_verification,
                    $user->email,
                    $user->nickname
                );
                if ($sendEmail) {
                    Yii::$app->session->setFlash('success', 'Ссылка для смены почты отправлена на почту');
                    return $this->redirect(Yii::$app->request->referrer);
                }
            }
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('password_varification', [
            'model' => $model
        ]);
    }

    public function actionResetPassword($token)
    {
        $model = PasswordChange::findOne(['password_verification' => $token]);
        $user = User::findOne(['password_verification' => $token]);
        if (!$model) {
            return $this->redirect(['authorization']);
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user->password = Yii::$app->security->generatePasswordHash($model->new_password);
            $user->save(false);
            Yii::$app->session->setFlash('success', 'пароль был изменен');

            return $this->redirect(Yii::$app->request->referrer);
        }
        $model->password = '';
        return $this->render('reset_password', [
            'model' => $model
        ]);
    }

    public function actionCartQuantity()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax) {

            $postContent = Yii::$app->request->post();
            $model = Products::findOne($postContent['product_id']);
            if ($postContent['quantity'] > $model->quantity) {
                return [
                    'exists' => false,
                    'max_quantity' => $model->quantity,
                    'message' => 'Such quantity does not exist!'
                ];
            }
            ProductService::updateCartProduct(Yii::$app->user->id, $postContent['product_id'], $postContent['quantity']);
            $sum = 0;
            foreach (ProductService::productListInCart(Yii::$app->user->id) as $cart) {
                if ($cart['product_discounted']) {
                    $sum += $cart['discounted_price'] * $cart['quantity'];
                } else {
                    $sum += $cart['original_price'] * $cart['quantity'];
                }
            }

            return [
                'exists' => true,
                'current_quantity' => $postContent['quantity'],
                'product_sum' => $sum
            ];
        }
    }

    public function actionDeleteAllCart()
    {
        Cart::deleteAll(['user_id' => Yii::$app->user->id]);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionBuy()
    {
        $userBalance = User::findOne(Yii::$app->user->id);
        $productBalance = ProductService::productSumPrice();
        if ($userBalance->balance < $productBalance) {
            Yii::$app->session->setFlash('danger', 'отсутствие баланса!');
            return $this->redirect(Yii::$app->request->referrer);
        }

        foreach (ProductService::productListInCart(Yii::$app->user->id) as $cart) {
            $product = Products::findOne($cart['product_id']);
            if ($product->quantity < $cart['quantity']) {
                Yii::$app->session->set(sprintf('Not enough quantity is available for the product %s!, 
                the some product may have been alreadt in your invertar', $product->title), true);
                return $this->redirect(['shop/']);
            }
            $sales = new Sales();
            $sales->product_id = $cart['product_id'];
            $sales->quantity = $cart['quantity'];
            $sales->user_id = Yii::$app->user->id;
            $sales->save();
            $product->quantity -= $cart['quantity'];
            $product->save(false);
        }
        $userBalance->balance -= $productBalance;
        $userBalance->save(false);
        Cart::deleteAll(['user_id' => Yii::$app->user->id]);
        Yii::$app->session->set('sale_active', true);
        return $this->redirect(['shop/finish-sale']);
    }

    public function actionFinishSale()
    {
        $checkSession = Yii::$app->session->get('sale_active');
        if ($checkSession) {
            Yii::$app->session->remove('sale_active');
            return $this->render('thanks_page');
        }
        return $this->redirect(['shop/products']);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $categories = ProductCategory::find()->all();
        $faq = Faq::findAll(['show_homepage' => true, 'is_active' => true]);
        $discountedProduct = Products::findOne(['is_discounted' => true, 'is_active' => true]);
        $bannerImage = Media::find()->one();
        $bannerImage ? $bannerImageTitle = sprintf('/uploads/%s', $bannerImage->image_path) : $bannerImageTitle = '/assets/img__hero.webp';
        return $this->render('index', [
            'categories' => $categories,
            'faq' => $faq,
            'bannerImage' => $bannerImage,
            'bannerImageTitle' => $bannerImageTitle,
            'discountedProduct' => $discountedProduct,
        ]);
    }


    public function actionProducts()
    {
        $searchModel = new ProductsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $categoryId = Yii::$app->request->get('product_category_id');
        if ($categoryId !== null) {
            $dataProvider->query->andFilterWhere(['product_category_id' => $categoryId]);
        }
        $dataProvider->pagination->pageSize = 36;
        return $this->render('products', [

views/shop/_modal_link.php
<div class="modal fade" id="modalLink" tabindex="-1" role="dialog" data-bs-backdrop="static"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="exampleModalLabel">Ваша ссылка для вывода вещей в игру
                    готова</h5>
            </div>
            <div class="modal-body">
                <center>
                    <img src="/img/withdraw-smile.png" alt="">
                </center>
                <p class="text-center">
                    Нажмите на ссылку, чтобы перейти на приватный сервер и забрать свои предметы
                </p>
                <p class="text-center"> Ник админа: cheburek_stock7</p>
                <a target="_blank" class="pop-up__withdraw__btn"
                   href="https://www.roblox.com/games/142823291?privateServerLinkCode=78607198115526072171061109913657">https://www.roblox.com/games/142823291?privateServerLinkCode=78607198115526072171061109913657</a>

                <p class="text-center">
                    если не можете зайти на вип сервер , то отправьте заявку в друзья боту
                </p>
                <a target="_blank" class="pop-up__withdraw__btn" href="https://www.roblox.com/users/4616739045/profile">https://www.roblox.com/users/4616739045/profile</a>
            </div>
            <div class="modal-footer">
                <a href="<?= \yii\helpers\Url::to(['shop/inventar']) ?>">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Отмена</button>
                </a>
            </div>
        </div>
    </div>
</div>

views/shop/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/shop/authorization.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

$this->title = 'Вход';
?>

<div class="page__main">
    <section class="section">
        <div class="container">
            <?php $form = ActiveForm::begin([
                'options' => ['class' => 'form form--login']
            ]); ?>

            <h2 class="form__title"><?= Html::encode($this->title) ?></h2>
            <div class="form__grid">
                <?= $form->field($model, 'username', [
                    'template' => '<div class="field"><label class="field__inner">{input}</label></div>{error}',
                    'inputOptions' => [
                        'class' => 'input field__input',
                        'placeholder' => 'Почта',
                        'pattern' => '[w-\.]+@([w-]+\.)+[w-]{2,4}$'
                    ],
                ]) ?>

                <?= $form->field($model, 'password', [
                    'template' => '<div class="field"><label class="field__inner">{input}<div class="field__show"><svg class="field__icon field__eye"><use href="img/svgSprite.svg#icon__eye"></use></svg><svg class="field__icon field__eye-off"><use href="img/svgSprite.svg#icon__eye--off"></use></svg></div></label></div>{error}',
                    'inputOptions' => [
                        'class' => 'input field__input',
                        'placeholder' => 'Пароль',
                    ],
                ])->passwordInput() ?>

                <div class="field field--flex">
                    <?= $form->field($model, 'rememberMe', [
                        'template' => '<label class="checkbox">{input}<span class="checkbox__fake-input"></span><span class="checkbox__label">{label}</span>{error}</label>',
                    ])->checkbox([
                        'class' => 'checkbox__input',
                    ], false) ?>
                    <?= Html::a('Забыл пароль', ['shop/password-varification'], ['class' => 'form__forget']) ?>
                </div>


                <?= Html::submitButton('Войти', ['class' => 'button button--primary form__button']) ?>
            </div>
            <?= Html::a('Регистрация', ['shop/registration'], ['class' => 'form__link']) ?>

            <?php ActiveForm::end(); ?>
        </div>
    </section>
</div>
<style>
    .input:-webkit-autofill, .input:-webkit-autofill:hover, .input:-webkit-autofill:focus {
        -webkit-text-fill-color:none !important
    }
</style>

views/shop/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::class, [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/shop/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/shop/index.php
<div class="page__main">
    <section class="hero"><img class="hero__image" src="<?=$bannerImageTitle?>" alt="Лучший магазин MM2"></section>
    <section class="section collection">
        <div class="container">
            <h2 class="section__title  section__title--ginger">Наши коллекции
                <div class="section__after">
                    <svg class="section__texture">
                        <use href="img/svgSprite.svg#img__texture"></use>
                    </svg>
                </div>
            </h2>
            <div class="collection__grid">
                <?php use yii\helpers\Url;

                foreach ($categories as $category): ?>
                    <a target="_blank" class="collection__item"
                       href="<?= Url::to(['shop/products', 'product_category_id' => $category->id]) ?>">
                        <img class="collection__image" style="width: 396px;height: 282px"
                             src="/uploads/<?= $category->image ?>" alt="<?= $category->image ?>">
                        <h3 class="collection__title"><?= $category->title ?></h3>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
    <?php if ($discountedProduct): ?>
        <section class="discount">
            <div class="container">
                <div class="discount__inner">
                    <h2 class="discount__title"><?= $discountedProduct->discount_text ?></h2>
                    <div class="discount__card"><img class="discount__card-image"
                                                     src="/uploads/<?= $discountedProduct->image ?>"
                                                     alt="<?= $discountedProduct->image ?>">
                        <div class="discount__card-info">
                            <div class="discount__card-title"><?= $discountedProduct->title ?></div>
                            <div class="discount__card-row">
                                <div class="discount__card-old-price"><?= $discountedProduct->original_price ?> ₽</div>
                                <div class="discount__card-price"><?= $discountedProduct->discounted_price ?> ₽</div>
                            </div>
                            <div class="discount__card-actions">
                                <filedset class="number discount__number" data-quantity="data-quantity">
                                    <button class="number__button number__button--sub" type="button">−
                                        <!--+icon('minus')(class='number__icon')--></button>
                                    <button class="number__button number__button--add" type="button">+
                                        <!--+icon('plus')(class='number__icon')--></button>
                                    <input class="number__input discount__number" type="number" min="1" max="1"
                                           value="1"
                                           pattern="[0-9]+"/></filedset>
                                <a style="text-decoration: none"
                                   href="<?= Url::to(['shop/add-to-cart', 'product_id' => $discountedProduct->id]) ?>">
                                    <button class="button discount__button card-product__button"><span
                                                class="button__title">В корзину</span></button>
                                </a>

                            </div>
                            <div class="discount__small"><?= $discountedProduct->discount_product_description ?></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <?php endif; ?>
    <section class="section faq">
        <div class="container">
            <h2 class="section__title  section__title--aqua">Вопрос-Ответ
                <div class="section__after">
                    <svg class="section__texture">
                        <use href="img/svgSprite.svg#img__texture"></use>
                    </svg>
                </div>
            </h2>
            <div class="faq__grid">
                <?php foreach ($faq as $faqSingle): ?>
                    <div class="faq__item">
                        <div class="faq__head">
                            <h3 class="faq__title"><?= $faqSingle->question ?></h3>
                            <button class="faq__trigger">+</button>
                        </div>
                        <div class="faq__body">
                            <div class="faq__inner">
                                <?php if ($faqSingle->content_is_video) : ?>
                                    <div class="faq__video">
                                        <iframe src="https://www.youtube.com/embed/<?= $faqSingle->video_url ?>"
                                                frameborder="0"
                                                allow="accelerometer; encrypted-media; gyroscope; web-share"
                                                allowfullscreen=""></iframe>
                                    </div>
                                <?php else : ?>
                                    <p class="faq__text"><?= $faqSingle->content_text ?></p>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
</div>

views/shop/inventar.php
<div class="page__main">
    <section class="section">
        <div class="container container--wide">
            <h2 class="section__title  section__title--ginger">Инвентарь
                <div class="section__after">
                    <svg class="section__texture">
                        <use href="/img/svgSprite.svg#img__texture"></use>
                    </svg>
                </div>
            </h2>
            <div class="cols">
                <div class="cols__aside">
                    <div class="inventory">
                        <div class="inventory__inner">
                            <button class="button  button--tertiary inventory__button check_all" id="inventoryAllCheck"><span
                                        class="button__title">Выбрать все</span></button>

                            <button class="button  button--tertiary inventory__button uncheck_all"
                                    id="inventoryUncheck"><span
                                        class="button__title">Снять выделение</span></button>
                            <button class="button  button--primary inventory__submit">
                                <span class="button__title">Вывести предметы</span>
                            </button>
                        </div>
                    </div>
                </div>
                <?php if(empty($inventars)):?>
                    <div style="height: 60px" class="alert alert-danger" role="alert">
                        Товар не найден
                    </div>
                <?php endif;?>
                <div class="cols__grid">

                    <?php use app\modules\management\services\ProductService;

                    foreach ($inventars as $inventar) : ?>
                    <?php if ($inventar->reserved_datetime && ProductService::checkSession($inventar->reserved_datetime)) : ?>
                            <input class="card-inventory__checkbox" value="<?= $inventar->id ?>" type="checkbox">
                            <div class="card-inventory__inner">
                                <img class="card-inventory__img" src="/uploads/<?= $inventar->product->image ?>"
                                     alt="<?= $inventar->product->image ?>">
                                <div class="card-inventory__info">
                                  <button class="btn btn-info" data-bs-toggle="modal" data-bs-target="#modalLink"> Продолжить вывод</button>
                                </div>
                            </div>
                    <?php else : ?>
                            <label class="card-inventory">
                                <input class="card-inventory__checkbox" value="<?= $inventar->id ?>" type="checkbox">
                                <div class="card-inventory__inner">
                                    <img class="card-inventory__img" src="/uploads/<?= $inventar->product->image ?>"
                                         alt="<?= $inventar->product->image ?>">
                                    <div class="card-inventory__info">
                                        <div class="card-inventory__title"><?= $inventar->product->title ?></div>
                                        <div class="card-inventory__row">
                                            <div class="card-inventory__price">
                                                <span><?= $inventar->product->original_price ?></span> ₽
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </label>
                    <?php endif; ?>
                    <?php endforeach; ?>

                </div>
            </div>
        </div>
    </section>
</div>

<?=Yii::$app->controller->renderPartial('_modal_nickname')?>
<?=Yii::$app->controller->renderPartial('_modal_link')?>

views/shop/passwordResetToken.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */

$resetLink = Yii::$app->urlManager->createAbsoluteUrl(['site/reset-password', 'token' => 'abs123']);
?>
<div style="background-color: #f6f6f6; padding: 20px;">
    <div style="max-width: 600px; margin: 0 auto;">
        <div style="background: #fff; padding: 30px; text-align: center; border-radius: 5px;">
            <h2 style="color: #333;">Hello, Alfraganus!</h2>
            <p style="font-size: 16px; color: #333; margin-top: 20px;">
                You have requested a password reset. Click the button below to reset your password.
            </p>

            <p style="margin: 40px 0;">
                <?= Html::a('Reset password', $resetLink, ['class' => 'reset-button', 'style' => 'background: #3490dc; border: none; color: #fff; cursor: pointer; font-size: 18px; padding: 10px 20px; text-decoration: none; border-radius: 5px;']) ?>
            </p>

            <p style="font-size: 16px; color: #999;">
                If you did not request a password reset, no further action is required.
            </p>
        </div>
    </div>
</div>

views/shop/password_varification.php
<div class="page__main">
    <section class="section">
        <div class="container">
            <?php use yii\helpers\Html;
            use yii\helpers\Url;
            use yii\widgets\ActiveForm;

            $form = ActiveForm::begin([
                'options' => ['class' => 'form form--forget'],
            ]) ?>

            <h2 class="form__title">Забыл пароль</h2>
            <p class="form__text">Введите свою электронную почту и мы вышлем вам ссылку для сброса пароля</p>

            <div class="form__grid">
                <div class="field">
                    <?= $form->field($model, 'email', [
                        'template' => '<label class="field__inner">{input}</label>',
                        'options' => ['class' => 'field__input'],
                    ])->input('email', ['class' => 'input field__input', 'placeholder' => 'Почта', 'pattern' => '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$']) ?>
                </div>

                <?= Html::submitButton('Сбросить пароль', ['class' => 'button button--primary form__button']) ?>
            </div>

            <?= Html::a('Я вспомнил пароль', Url::to(['shop/authorization']), ['class' => 'form__link']) ?>

            <?php ActiveForm::end() ?>
        </div>
    </section>
</div>

views/shop/thanks_page.php
<?php

use yii\helpers\Url;

?>
<div class="page__main">
<div class="vh-100 d-flex justify-content-center align-items-center">
    <div>
        <div class="mb-4 text-center">
            <center>
            <svg xmlns="http://www.w3.org/2000/svg" class="text-success" width="75" height="75"
                 fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                <path
                        d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
            </svg>
            </center>
        </div>
        <div class="text-center">
            <h1>Спасибо за покупку!</h1>
            <p>Мы отправили ссылку на вашу электронную почту для дальнейших инструкций </p>
            <a href="<?=Url::to(['shop/products'])?>">
                <button class="btn btn-primary">Продолжить покупки</button>
            </a>
        </div>
    </div>
</div>
    <style>
        .page__main {
            padding-top: 0!important;
        }
    </style>